# Generated by Django 5.2.7 on 2025-11-05 14:05

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


def seed_size_templates(apps, schema_editor):
    ApparelItem = apps.get_model("catalog", "ApparelItem")
    CollectionSizeTemplate = apps.get_model("catalog", "CollectionSizeTemplate")
    ApparelItemSizeInventory = apps.get_model("catalog", "ApparelItemSizeInventory")

    for item in ApparelItem.objects.all():
        if not getattr(item, "size", None):
            continue
        initial_quantity = getattr(item, "edition_size", None) or item.quantity_remaining
        template, created = CollectionSizeTemplate.objects.get_or_create(
            collection_id=item.collection_id,
            size=item.size,
            defaults={"quantity": initial_quantity},
        )
        if not created and template.quantity < initial_quantity:
            template.quantity = initial_quantity
            template.save(update_fields=["quantity"])
        ApparelItemSizeInventory.objects.update_or_create(
            item_id=item.pk,
            size=item.size,
            defaults={
                "quantity_initial": initial_quantity,
                "quantity_remaining": item.quantity_remaining,
            },
        )


def noop_reverse(apps, schema_editor):
    """Reverse operation intentionally left blank."""


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_apparelitem_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApparelItemSizeInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=3,
                    ),
                ),
                ("quantity_initial", models.PositiveIntegerField()),
                ("quantity_remaining", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_inventories",
                        to="catalog.apparelitem",
                    ),
                ),
            ],
            options={
                "ordering": ("size", "id"),
                "unique_together": {("item", "size")},
            },
        ),
        migrations.CreateModel(
            name="CollectionSizeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="Предустановленное количество вещей этого размера"
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="size_templates",
                        to="catalog.collection",
                    ),
                ),
            ],
            options={
                "ordering": ("collection", "size"),
                "unique_together": {("collection", "size")},
            },
        ),
        migrations.AddField(
            model_name="apparelitem",
            name="access_code",
            field=models.CharField(
                default=catalog.models.generate_access_code,
                editable=False,
                help_text="Уникальный код доступа к подробной информации о вещи",
                max_length=16,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_size_templates, reverse_code=noop_reverse),
        migrations.RemoveField(
            model_name="apparelitem",
            name="background_image",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="edition_size",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="modifications",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="product_url",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="quantity_remaining",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="size",
        ),
    ]
