# Generated by Django 5.2.7 on 2025-11-05 14:44

import catalog.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_remove_apparelitem_background_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apparelitem",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="access_code",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="acquired_at",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="apparelitem",
            name="qr_code_url",
        ),
        migrations.AddField(
            model_name="apparelitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apparelitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ApparelUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("XS", "XS"),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        default=catalog.models.generate_access_code,
                        editable=False,
                        help_text="Уникальный код доступа к конкретной вещи",
                        max_length=16,
                        unique=True,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True, help_text="Ссылка на QR-код страницы вещи."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="catalog.apparelitem",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Пользователь, которому принадлежит вещь.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apparel_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("item", "size", "id"),
            },
        ),
    ]
